name: Semgrep SAST

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run Semgrep (OWASP Top 10)
        run: |
          semgrep --version
          semgrep scan --config p/owasp-top-ten --metrics=off
